/**
 * RoadResQ Master Data Store
 * Contains realistic Indian seed data and state store for User, Provider, and Admin roles.
 */

export const DB = {
  users: [
    {
      id: 'usr_main',
      name: 'Dhruv Patel',
      email: 'dhruv.patel@roadresq.in',
      phone: '+91 98765 43210',
      role: 'USER',
      avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      createdAt: '2026-01-10T10:00:00.000Z',
    },
    {
      id: 'usr_2',
      name: 'Priya Sharma',
      email: 'priya.sharma@roadresq.in',
      phone: '+91 98450 99887',
      role: 'USER',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      createdAt: '2026-02-14T08:30:00.000Z',
    },
  ],

  vehicles: [
    {
      id: 'veh_1',
      userId: 'usr_main',
      make: 'Tata',
      model: 'Nexon EV Empowered',
      year: 2024,
      plateNumber: 'GJ 01 AB 1234',
      color: 'Intensi-Teal',
      type: 'ev',
      fuelType: 'Electric',
      createdAt: '2026-01-10T10:15:00.000Z',
    },
    {
      id: 'veh_2',
      userId: 'usr_main',
      make: 'Hyundai',
      model: 'Creta 1.5 SX(O)',
      year: 2023,
      plateNumber: 'GJ 01 CD 5678',
      color: 'Polar White',
      type: 'suv',
      fuelType: 'Petrol',
      createdAt: '2026-01-12T14:20:00.000Z',
    },
    {
      id: 'veh_3',
      userId: 'usr_main',
      make: 'Royal Enfield',
      model: 'Hunter 350',
      year: 2023,
      plateNumber: 'GJ 01 EF 9012',
      color: 'Dapper Ash',
      type: 'bike',
      fuelType: 'Petrol',
      createdAt: '2026-02-01T09:00:00.000Z',
    },
  ],

  providers: [
    {
      id: 'prov_1',
      name: 'Shree Auto Care (Rajesh Patel)',
      email: 'shreeautocare@roadresq.in',
      phone: '+91 98250 12345',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      vehicleType: 'Mobile Service Van',
      vehiclePlate: 'GJ 01 TC 7711',
      rating: 4.88,
      jobsCompleted: 842,
      earningsTotal: 142500.0,
      earningsToday: 3450.0,
      status: 'AVAILABLE',
      verificationStatus: 'VERIFIED',
      currentLat: 23.0225,
      currentLng: 72.5714, // Ahmedabad (Satellite / SG Highway)
      skills: ['FLAT_TYRE', 'DEAD_BATTERY', 'OUT_OF_FUEL', 'MECHANICAL', 'OVERHEATING', 'DONT_KNOW'],
      isOnline: true,
    },
    {
      id: 'prov_2',
      name: 'Gujarat 24/7 Heavy Towing (Vikram Sinh)',
      email: 'gujarattowing@roadresq.in',
      phone: '+91 98251 55667',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      vehicleType: 'Hydraulic Flatbed Tow Truck',
      vehiclePlate: 'GJ 01 TOW 9022',
      rating: 4.92,
      jobsCompleted: 610,
      earningsTotal: 218000.0,
      earningsToday: 4800.0,
      status: 'AVAILABLE',
      verificationStatus: 'VERIFIED',
      currentLat: 23.0338,
      currentLng: 72.5135, // SG Highway / Bodakdev
      skills: ['TOWING', 'OVERHEATING', 'MECHANICAL', 'DONT_KNOW'],
      isOnline: true,
    },
    {
      id: 'prov_3',
      name: 'QuickFix Battery & Tyre Squad (Mohammed Irfan)',
      email: 'quickfix@roadresq.in',
      phone: '+91 98252 88990',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      vehicleType: 'Quick Response Bike',
      vehiclePlate: 'GJ 01 MOTO 104',
      rating: 4.91,
      jobsCompleted: 420,
      earningsTotal: 96000.0,
      earningsToday: 2100.0,
      status: 'AVAILABLE',
      verificationStatus: 'VERIFIED',
      currentLat: 23.0130,
      currentLng: 72.5350, // Prahladnagar
      skills: ['DEAD_BATTERY', 'OUT_OF_FUEL', 'FLAT_TYRE', 'DONT_KNOW'],
      isOnline: true,
    },
    {
      id: 'prov_4',
      name: 'Sri Krishna Auto Pro (Rajesh Kumar)',
      email: 'srikrishna@roadresq.in',
      phone: '+91 98450 22334',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      vehicleType: 'Mobile Service Patrol',
      vehiclePlate: 'KA 01 MH 7711',
      rating: 4.95,
      jobsCompleted: 1040,
      earningsTotal: 185000.0,
      earningsToday: 3200.0,
      status: 'AVAILABLE',
      verificationStatus: 'VERIFIED',
      currentLat: 12.9352,
      currentLng: 77.6245, // Bengaluru (Koramangala)
      skills: ['FLAT_TYRE', 'DEAD_BATTERY', 'OUT_OF_FUEL', 'MECHANICAL', 'OVERHEATING', 'DONT_KNOW'],
      isOnline: true,
    },
  ],

  incidents: [
    {
      id: 'RRQ-2026-004281',
      userId: 'usr_main',
      userName: 'Dhruv Patel',
      userPhone: '+91 98765 43210',
      vehicleId: 'veh_1',
      vehicle: {
        make: 'Tata',
        model: 'Nexon EV Empowered',
        plateNumber: 'GJ 01 AB 1234',
        type: 'ev',
      },
      breakdownType: 'DEAD_BATTERY',
      severity: 'MEDIUM',
      latitude: 23.0225,
      longitude: 72.5714,
      address: 'Satellite Road, Near ISRO, Satellite, Ahmedabad, Gujarat 380015',
      landmark: 'Opposite Star Bazaar',
      notes: '12V Auxiliary battery completely drained while parked.',
      status: 'CLOSED',
      safetyPin: '4819',
      etaMinutes: 0,
      providerId: 'prov_1',
      createdAt: '2026-03-18T14:32:00.000Z',
      timeline: [
        { status: 'CREATED', title: 'Incident Created', description: 'Battery jumpstart requested', timestamp: '14:32' },
        { status: 'MATCHING', title: 'Smart Match', description: 'Matched with Shree Auto Care', timestamp: '14:33' },
        { status: 'ASSIGNED', title: 'Job Assigned', description: 'Dispatched to Rajesh Patel (4.88★)', timestamp: '14:33' },
        { status: 'EN_ROUTE', title: 'Provider En Route', description: 'Technician driving on Satellite Road', timestamp: '14:34' },
        { status: 'ARRIVED', title: 'Provider Arrived', description: 'Safety PIN verified on-site', timestamp: '14:44' },
        { status: 'SERVICE', title: 'Service Completed', description: 'EV 12V Auxiliary Jumpstart & Health Test', timestamp: '14:55' },
        { status: 'PAYMENT', title: 'Invoice Paid', description: 'Paid ₹480 via UPI', timestamp: '14:58' },
        { status: 'CLOSED', title: 'Incident Closed', description: '5-star review given', timestamp: '15:00' },
      ],
      escalationLogs: [],
      invoice: {
        id: 'INV-2026-004281',
        incidentId: 'RRQ-2026-004281',
        baseFee: 350.0,
        labourFee: 150.0,
        partsFee: 60.0,
        discount: 80.0,
        tax: 38.0,
        total: 518.0,
        isPaid: true,
        paymentMethod: 'UPI',
        paidAt: '2026-03-18T14:58:00.000Z',
      },
      review: {
        rating: 5,
        feedback: 'Super fast jumpstart for my Nexon EV. Rajesh was courteous and reached in 10 mins!',
        tags: 'Punctual, Professional, EV Expert',
      },
    },
  ],

  notifications: [
    {
      id: 'notif_1',
      userId: 'usr_main',
      title: 'RoadResQ Telematics Grid Active',
      message: '24/7 Smart Emergency Dispatch & Towing Network is online across India.',
      type: 'INFO',
      read: false,
      createdAt: new Date().toISOString(),
    },
  ],
};
